on:
    workflow_dispatch:   # allow running the workflow manually from the GitHub UI
    push:
        branches: main
    pull_request:
        branches:
            - '*'           #Run the workflow for all pull requests

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                versionSpec: 5.x
            - name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.7
              id: gitversion
            - name: Display GitVersion outputs
              run: |
                echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
                echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: "20"
            - run: npm ci
            - run: npm test
            - uses: JS-DevTools/npm-publish@v3
              with:
                token: ${{ secrets.NPM_TOKEN }}