on:
    workflow_dispatch:   # allow running the workflow manually from the GitHub UI
    push:
        branches: main
    pull_request:
        branches:
            - '*'           #Run the workflow for all pull requests

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: "20"
            - name: Install dependencies
              run: |
                if [ -e package-lock.json ]; then
                npm ci
                else
                npm i
                fi
            - run: npm test
            - run: npm run build
            - run: npm run semantic-release
              env:
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
