on:
    workflow_dispatch:   # allow running the workflow manually from the GitHub UI
    push:
        branches: main
    pull_request:
        branches:
            - '*'           #Run the workflow for all pull requests

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: "20"
            - run: npm ci
            - run: npm test
            - uses: JS-DevTools/npm-publish@v3
              with:
                token: ${{ secrets.NPM_TOKEN }}